#ifndef ALLO_STATUS_H
#define ALLO_STATUS_H

enum allo_status {
  ALLO_OK = 0,
  ALLO_OOM,
  ALLO_ERR_NULL,
  ALLO_ERR_INVALID_SIZE,
  ALLO_ERR_INVALID_ALIGN,
  ALLO_ERR_MEM_NOT_ALIGNED,
  ALLO_ERR_OUT_OF_BOUNDS,
};

#endif // !ALLO_STATUS_H
