name: Build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linux-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]
        compiler: [{name: gcc, version: 14}, {name: clang, version: 18}]

    env:
      COMPILER: ${{ matrix.compiler.name }}-${{ matrix.compiler.version }}

    steps:
      - uses: actions/checkout@v6

      - name: Update system
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install $COMPILER clang-format

      - name: List versions
        run: |
          $COMPILER --version
          clang-format --version

      - name: Run formatter check
        run: > 
          find include src tests
          -type f \( -name "*.c" -o -name "*.h" \)
          -exec clang-format --dry-run {} +

      - name: Configure
        run: > 
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=$COMPILER
          -DENABLE_SANITIZERS=${{ matrix.build_type == 'Debug' && 'ON' || 'OFF' }}

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure

