name: Build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linux-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]
        compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v6

      - name: Configure
        env:
          CC: ${{ matrix.compiler }}
        run: > 
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=${{ matrix.compiler }}
          -DENABLE_SANITIZERS=${{ matrix.build_type == 'Debug' && 'ON' || 'OFF' }}

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure

  windows-build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v6

      - name: Configure
        run: >
          cmake -S . -B build
          --config=${{ matrix.build }}

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure
